laptop/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from laptop.views import index, LaptopListar, LaptopCrear, LaptopEditar, LaptopBorrar, \
						 IncidenteListar, IncidenteCrear, IncidenteEditar, IncidenteBorrar

urlpatterns = [
#    url(r'^$', index, name='index'),
    url(r'^$', login_required(LaptopListar.as_view()), name='listar_laptop'),
    url(r'^listar/', login_required(LaptopListar.as_view()), name='listar_laptop'),
    url(r'^crear/', login_required(LaptopCrear.as_view()), name='crear_laptop'),
    
    url(r'^editar_laptop/(?P<pk>\d+)/$', login_required(LaptopEditar.as_view()), name='editar_laptop'),
    url(r'^borrar_laptop/(?P<pk>\d+)/$', login_required(LaptopBorrar.as_view()), name='borrar_laptop'),

    url(r'^listar_incidente/', login_required(IncidenteListar.as_view()), name='listar_incidente'),
    url(r'^crear_incidente/', login_required(IncidenteCrear.as_view()), name='crear_incidente'),

    url(r'^editar_incidente/(?P<pk>\d+)/$', login_required(IncidenteEditar.as_view()), name='editar_incidente'),
    url(r'^borrar_incidente/(?P<pk>\d+)/$', login_required(IncidenteBorrar.as_view()), name='borrar_incidente'),
]

racii/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

# password reset
from django.contrib.auth import views as auth_views

import django.views.defaults

def custom_page_not_found(request):
    return django.views.defaults.page_not_found(request, None)


urlpatterns = [
    url(r'^', include('laptop.urls', namespace='index')),
    url(r'^admin/', admin.site.urls),
    url(r'^laptop/', include('laptop.urls', namespace='laptop')),
    url(r'^escuela/', include('escuela.urls', namespace='escuela')),
    url(r'^donante/', include('donante.urls', namespace='donante')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    #url(r'^404/$', django.views.defaults.page_not_found, ),
    url(r'^404/', custom_page_not_found),
    # password_reset
    #url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    #url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.password_reset_confirm, name='password_reset_confirm'),
    #url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <script src="{% static 'jquery-3.3.1.min.js' %}" type="text/javascript"></script>
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  {% block extrastatic %}
  {% endblock %}
	<!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.minty.css' %}">
  -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.simplex.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  <!-- Latest compiled and minified CSS -->

<title>
  {% block title %}
  RACII
  {% endblock %}
</title>
</head>

{% block navbar %}
<body>
  <div class="container">
    <nav class="navbar navbar-fixed-top>
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'laptop:listar_laptop' %}">RACII</a>
        </div>
        <ul class="nav navbar-nav">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Laptops<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/laptop/listar/">Listar laptops</a></li>
              <li><a href="/laptop/crear/">Agregar laptops</a></li>
              <li class="divider"></li>
              <li><a href="/laptop/listar_incidente/">Listar incidentes</a></li>
              <li><a href="/laptop/crear_incidente/">Agregar incidentes</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Escuelas<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/escuela/listar_persona/">Listar personas</a></li>
              <li><a href="/escuela/crear_persona/">Agregar personas</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/listar_escuela/">Listar Escuelas</a></li>
              <li><a href="/escuela/crear_escuela/">Agregar Escuelas</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/listar_visitaa/">Listar Visita A</a></li>
              <li><a href="/escuela/listar_visitab/">Listar Visita B</a></li>
              <li><a href="/escuela/crear_visita/">Agregar Visita</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Donantes <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/escuela/listar_donante/">Listar Donantes</a></li>
              <li><a href="/escuela/crear_donante/">Agregar Donantes</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/admin/">Administrar</a></li>
          <li><a href="{% url 'logout' %}"> Salir</a></li>
        </ul>
      </div>
    </nav>
  </div>

  <div class="container">
    <nav class="navbar navbar-fixed-top>
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'laptop:listar_laptop' %}">RACII</a>
        </div>
        <ul class="nav navbar-nav">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Laptops<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/laptop/listar/">Listar laptops</a></li>
              <li><a href="/laptop/crear/">Agregar laptops</a></li>
              <li class="divider"></li>
              <li><a href="/laptop/listar_incidente/">Listar incidentes</a></li>
              <li><a href="/laptop/crear_incidente/">Agregar incidentes</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Escuelas<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/escuela/listar_persona/">Listar personas</a></li>
              <li><a href="/escuela/crear_persona/">Agregar personas</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/listar_escuela/">Listar Escuelas</a></li>
              <li><a href="/escuela/crear_escuela/">Agregar Escuelas</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/listar_visitaa/">Listar Visita A</a></li>
              <li><a href="/escuela/listar_visitab/">Listar Visita B</a></li>
              <li><a href="/escuela/crear_visita/">Agregar Visita</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Donantes <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/escuela/listar_donante/">Listar Donantes</a></li>
              <li><a href="/escuela/crear_donante/">Agregar Donantes</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/admin/"><span class="glyphicon glyphicon-user"></span> Administrar</a></li>
          <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Salir</a></li>
        </ul>
      </div>
    </nav>
  </div>

  <div class="container">

    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block extrahead %}
    {% endblock %}

    {% block scripts %}
    {% endblock %}

    {% block footer %}
    {% endblock %}
</body>
</html>

templates/base/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">

<!-- head -->
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>

  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js"
    integrity="sha256-o8aByMEvaNTcBsw94EfRLbBrJBI+c3mjna/j4LrfyJ8="
    crossorigin="anonymous">
  </script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

<!-- -->

  <!--   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.css" />


    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.js"></script>
 -->

<!-- -->
  {% block extrastatic %}
  {% endblock %}

<!-- block extrastatic -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.lumen.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.js"></script>

  <link rel='stylesheet'
  href='https://use.fontawesome.com/releases/v5.7.0/css/all.css'
  integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ'
  crossorigin='anonymous'>
  <title>
    {% block title %}
    OLPC Inventario
    {% endblock %}
  </title>
</head>

{% block navbar %}
<body>
<div class="container">

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'laptop:listar_laptop' %}">
            <!--<img src="http://lavidau.files.wordpress.com/2009/09/olpc-logo.jpg" width="50" height="40">Inventario</a>-->
            Inventario</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="fas fa-laptop"></span>  Laptops<span class="caret "></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/laptop/listar/">Listar laptops</a></li>
              <li class="divider"></li>
              <li><a href="/laptop/crear/">Agregar laptops</a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="fas fa-bug"></span>  Incidentes<span class="caret "></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/laptop/listar_incidente/">Listar incidentes</a></li>
              <li class="divider"></li>
              <li><a href="/laptop/crear_incidente/">Agregar incidentes</a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="fas fa-users"></span>  Personas<span class="caret "></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/escuela/listar_persona/">Listar personas</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/crear_persona/">Agregar personas</a></li>
            </ul>
          </li>


          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class=" fas fa-school"></span>	Escuelas<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">

              <li><a href="/escuela/listar_escuela/">Listar Escuelas</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/crear_escuela/">Agregar Escuelas</a></li>
            </ul>
          </li>
          
          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="fas fa-briefcase"></span>	Donantes <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/escuela/listar_donante/">Listar Donantes</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/crear_donante/">Agregar Donantes</a></li>
            </ul>
          </li> -->

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="fas fa-clipboard-list"></span>	Logística<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/escuela/listar_visita/">Listar Visita</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/crear_visita/">Agregar Visita</a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="fas fa-chart-pie"></span>  Reporteria<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/escuela/reporte1">Inventario de laptops</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/reporte2">Estado de los incidentes de laptops</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/reporte3">Distribucion por tipos de incidentes de Laptops</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/reporte4">Componentes reportados en los incidentes</a></li>
              <li class="divider"></li>
              <li><a href="/escuela/reporte5">Reporte 5 </a></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="/admin/"><span class="fas fa-wrench"></span> Administrar</a></li>
          <li><a href="{% url 'logout' %}"><span class="fas fa-sign-out-alt"></span> Salir</a></li>
        </ul>

      </div>
    </div>
  </nav>
</div>

<div class="container">

  {% endblock %}

  {% block content %}
  {% endblock %}

  {% block extrahead %}
  {% endblock %}

  {% block scripts %}
  {% endblock %}

  {% block footer %}
  {% endblock %}
</body>
</html>