escuela/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from escuela.views import (
    PersonaListar, 
    PersonaCrear, 
    PersonaEditar, 
    PersonaBorrar, 
    EscuelaListar, 
    EscuelaCrear, 
    VisitaCrear, 
    VisitaListar, 
    VisitaEditar, 
    VisitaBorrar,
    VisitaVer
    )
from escuela.views import (
    ChartData, IncidentesData1, IncidentesData2, IncidentesData3, Reporte1, Reporte2, 
    Reporte3, Reporte4, 
    Reporte5)
from donante.views import DonanteListar, DonanteCrear, DonanteEditar, DonanteBorrar

urlpatterns = [
#    url(r'^$', index, name='index'),
    url(r'^listar_persona/', login_required(PersonaListar.as_view()), name='listar_persona'),
    url(r'^crear_persona/', login_required(PersonaCrear.as_view()), name='crear_persona'),    
    url(r'^editar_persona/(?P<pk>\d+)/$', login_required(PersonaEditar.as_view()), name='editar_persona'),
    url(r'^borrar_persona/(?P<pk>\d+)/$', login_required(PersonaBorrar.as_view()), name='borrar_persona'),

    url(r'^listar_escuela/', login_required(EscuelaListar.as_view()), name='listar_escuela'),
    url(r'^crear_escuela/', login_required(EscuelaCrear.as_view()), name='crear_escuela'),

	url(r'^listar_donante/', login_required(DonanteListar.as_view()), name='listar_donante'),
	url(r'^crear_donante/', login_required(DonanteCrear.as_view()), name='crear_donante'),
    url(r'^editar_donante/(?P<pk>\d+)/$', login_required(DonanteEditar.as_view()), name='editar_donante'),
    url(r'^borrar_donante/(?P<pk>\d+)/$', login_required(DonanteBorrar.as_view()), name='borrar_donante'),

    url(r'^crear_visita/', login_required(VisitaCrear.as_view()), name='crear_visita'),
    url(r'^listar_visita/', login_required(VisitaListar.as_view()), name='listar_visita'),
    
    url(r'^ver_visita/(?P<pk>\d+)/$', login_required(VisitaVer.as_view()), name='ver_visita'),

    url(r'^editar_visita/(?P<pk>\d+)/$', login_required(VisitaEditar.as_view()), name='editar_visita'),
    url(r'^borrar_visita/(?P<pk>\d+)/$', login_required(VisitaBorrar.as_view()), name='borrar_visita'),

    url(r'^api/chart/data/', ChartData.as_view()),
    url(r'^api/chart/incidentes_data1/', IncidentesData1.as_view()),
    url(r'^api/chart/incidentes_data2/', IncidentesData2.as_view()),
    url(r'^api/chart/incidentes_data3/', IncidentesData3.as_view()),
    url(r'^reporte1', Reporte1.as_view(), name='reporte1'),
    url(r'^reporte2', Reporte2.as_view(), name='reporte2'),
    url(r'^reporte3', Reporte3.as_view(), name='reporte3'),
    url(r'^reporte4', Reporte4.as_view(), name='reporte4'),
    url(r'^reporte5', Reporte5.as_view(), name='reporte5'),    
]

racii/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

# password reset
from django.contrib.auth import views as auth_views

import django.views.defaults

def custom_page_not_found(request):
    return django.views.defaults.page_not_found(request, None)


urlpatterns = [
    url(r'^', include('laptop.urls', namespace='index')),
    url(r'^admin/', admin.site.urls),
    url(r'^laptop/', include('laptop.urls', namespace='laptop')),
    url(r'^escuela/', include('escuela.urls', namespace='escuela')),
    url(r'^donante/', include('donante.urls', namespace='donante')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    #url(r'^404/$', django.views.defaults.page_not_found, ),
    url(r'^404/', custom_page_not_found),
    # password_reset
    #url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    #url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.password_reset_confirm, name='password_reset_confirm'),
    #url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

escuela/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from laptop.models import Laptop

from donante.models import Donante

# Create your models here.
class Departamento(models.Model):
	nombre = models.CharField(max_length=50)

	def __str__(self):
		return self.nombre

class Municipio(models.Model):
	nombre = models.CharField(max_length=50)

	def __str__(self):
		return self.nombre

class Escuela(models.Model):
	nombre = models.CharField(max_length=50)
	departamento = models.ForeignKey(Departamento, null=True, blank=True, on_delete=models.CASCADE)
	municipio = models.ForeignKey(Municipio, null=True, blank=True, on_delete=models.CASCADE)
	direccion = models.CharField(max_length=90)
	telefono = models.CharField(max_length=10, blank=True)
	donante = models.ForeignKey(Donante, null=True, blank=True, on_delete=models.CASCADE)

	def __str__(self):
		return self.nombre

class Persona(models.Model):
	ROL_E =(
		('K', 'Preescolar'),
		('1', '1-Primer'),
		('2', '2-Segundo'),
		('3', '3-Tercer'),
		('4', '4-Cuarto'),
		('5', '5-Quinto'),
		('6', '6-Sexto'),
		('D', 'Docente'),
		('P', 'Director'),
		('V', 'Voluntario'),
	)
	nombre = models.CharField(max_length=50)
	apellido = models.CharField(max_length=50)
	telefono = models.CharField(max_length=10, blank=True)
	laptop = models.OneToOneField(Laptop,null=True, blank=True, on_delete=models.CASCADE)
	escuela = models.ForeignKey(Escuela,null=True, blank=True, on_delete=models.CASCADE)
	grado = models.CharField(max_length=1, choices=ROL_E, blank=True)

	def __str__(self):
		return '{} {} {} {}'.format(self.nombre, self.laptop, self.escuela, self.grado)

	def grado_detalle(self):
		return dict(Persona.ROL_E)[self.grado]

class Visita(models.Model):
	T_VISITA = (
		('1', 'Educativa'),
		('2', 'Tecnico'),
		('3', 'Logistico'),
		)
	titulo = models.CharField(max_length=90)
	fecha = models.DateField()
	escuela = models.ForeignKey(Escuela, null=True, blank=False, on_delete=models.CASCADE)
	tipo_visita = models.CharField(max_length=1, choices=T_VISITA, blank=False)
	objetivo = models.CharField(max_length=90)
	descripcion = models.CharField(max_length=250)
	avances = models.CharField(max_length=250)

	def __str__(self):
		return '{} {} {}'.format(self.fecha, self.titulo, self.escuela, self.tipo_visita, )

	def visita_detalle(self):
		return dict(Visita.T_VISITA)[self.tipo_visita]

#class Conectividad(models.Model):

escuela/forms.py
from django import forms

from escuela.models import Persona, Escuela, Visita

from donante.models import Donante

class PersonaForm(forms.ModelForm):
	class Meta:
		model = Persona
		fields = [
			'nombre',
			'apellido',
			'telefono',
			'laptop',
			'escuela',
			'grado',
		]
		labels = {
			'nombre': 'Nombre',
			'apellido': 'Apellido',
			'telefono': 'Telefono',
			'laptop': 'Laptop',
			'escuela': 'Escuela',
			'grado': 'Grado',
		}
		widgets = {
			'nombre': forms.TextInput(
				attrs={
				'class':'form-control'
				}),
			'apellido': forms.TextInput(
				attrs={
				'class': 'form-control'
				}),
			'telefono': forms.TextInput(
				attrs={
				'class': 'form-control'
				}),
			'laptop': forms.Select(
				attrs={
				'class': 'selectpicker',
				'data-live-search':'true'
				}),
			'escuela': forms.Select(
				attrs={
				'class': 'selectpicker',
				'data-live-search':'true'
				}),
			'grado': forms.Select(
				attrs={
				'class': 'selectpicker',
				'data-live-search':'true'
				}),
		}

class EscuelaForm(forms.ModelForm):
	class Meta:
		model = Escuela
		fields = [
			'nombre',
			'departamento',
			'municipio',
			'direccion',
			'telefono',
			'donante',
		]
		labels = {
			'nombre': 'Nombre: ',
			'departamento': 'Departamento',
			'municipio': 'Municipio',
			'direccion': 'Direccion',
			'telefono': 'Telefono',
			'donante': 'Donante',
		}
		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'departamento': forms.Select(attrs={'class': 'form-control'}),
			'municipio': forms.Select(attrs={'class': 'form-control'}),
			'direccion': forms.TextInput(attrs={'class':'form-control'}),
			'telefono': forms.TextInput(attrs={'class':'form-control'}),
			'donante': forms.Select(attrs={'class': 'form-control'}),
		}

class VisitaForm(forms.ModelForm):
	class Meta:
		model = Visita

		fields = [
			'titulo',
			'fecha', 
			'escuela',
			'tipo_visita',
			'objetivo',
			'descripcion',
			'avances',
		]
		labels = {
			'titulo': 'Titulo de la visita',
			'fecha': 'Fecha de la visita', 
			'escuela': 'Escuela',
			'tipo_visita': 'Tipo de visita',
			'objetivo': 'Objetivo de la visita',
			'descripcion': 'Descripcion de la visita',
			'avances': 'Avances encontrados',
		}
		widgets = {
			'titulo':  forms.TextInput(attrs={'class':'form-control'}),
			'fecha':  forms.DateInput(format='%d/%m/%Y'),
			'escuela': forms.Select(attrs={'class':'form-control'}),
			'tipo_visita': forms.Select(attrs={'class':'form-control'}),
			'objetivo': forms.TextInput(attrs={'class':'form-control'}),
			'descripcion':forms.Textarea(attrs={
				'rows': '4',
				'placeholder': 'Describa las actividades realizadas durante la visita'
				}),
			'avances': forms.Textarea(attrs={
				'rows': '4',
				'placeholder': 'Describa los avances encontrados en la visita.'
				}),
		}

escuela/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect

from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy

from django.views.generic import View, ListView, CreateView, UpdateView, DeleteView, DetailView

from escuela.forms import PersonaForm, EscuelaForm, VisitaForm
from escuela.models import Persona, Escuela, Visita

from rest_framework.views import APIView
from rest_framework.response import Response

from django.contrib.auth import get_user_model
from laptop.models import Laptop, Incidente

from donante.models import Donante

# Create your views here.
class PersonaListar(ListView):
    model = Persona
    template_name = 'escuela/listar_persona.html'
    context_object_name = 'personas'  # Default: object_list
    paginate_by = 10
    queryset = Persona.objects.all()

class PersonaCrear(CreateView):
    model = Persona
    form_class = PersonaForm
    template_name = 'escuela/crear_persona.html'
    success_url = reverse_lazy('escuela:listar_persona')

class PersonaEditar(UpdateView):
    model = Persona
    form_class = PersonaForm
    template_name = 'escuela/crear_persona.html'
    success_url = reverse_lazy('escuela:listar_persona')

class PersonaBorrar(DeleteView):
    model = Persona
    template_name = 'escuela/borrar_persona.html'
    success_url = reverse_lazy('escuela:listar_persona')

class EscuelaListar(ListView):
    model = Escuela
    template_name = 'escuela/listar_escuela.html'

class EscuelaCrear(CreateView):
    model = Escuela
    form_class = EscuelaForm
    template_name = 'escuela/crear_escuela.html'
    success_url = reverse_lazy('escuela:listar_escuela')

class VisitaCrear(CreateView):
    model = Visita
    form_class = VisitaForm
    template_name = 'escuela/crear_visita.html'
    success_url = reverse_lazy('escuela:listar_visita')

class VisitaListar(ListView):
    model = Visita
    template_name = 'escuela/listar_visita.html'

class VisitaVer(DetailView):
    model = Visita
    template_name = 'escuela/ver_visita.html'

class VisitaEditar(UpdateView):
    model = Visita
    form_class = VisitaForm
    template_name = 'escuela/crear_visita.html'
    success_url = reverse_lazy('escuela:listar_visita')

class VisitaBorrar(DeleteView):
    model = Visita
    template_name = 'escuela/borrar_visita.html'
    success_url = reverse_lazy('escuela:listar_visita')

User = get_user_model()

class Reporte1(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'escuela/charts1.html')

class Reporte2(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'escuela/charts2.html')

class Reporte3(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'escuela/charts3.html')  

class Reporte4(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'escuela/charts4.html')

class Reporte5(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'escuela/charts5.html')

class ChartData(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        qs_xo_1 = Laptop.objects.filter(modelo=1).count()
        qs_xo_2 = Laptop.objects.filter(modelo=2).count()
        qs_xo_3 = Laptop.objects.filter(modelo=3).count()
        qs_xo_4 = Laptop.objects.filter(modelo=4).count()
        qs_nl3 = Laptop.objects.filter(modelo=5).count()
#       qs_escuela_1 = Persona.objects.filter(escuela='1').count()
#       qs_escuela_2 = Persona.objects.filter(escuela='2').count()
#       qs_escuela_3 = Persona.objects.filter(escuela='3').count()
#       qs_count = User.objects.all().count()
        data = {
            "labels": ["XO-1", "XO-1.5", "XO-1.75", "XO-4", "NL3"],
            "data": [qs_xo_1, qs_xo_2, qs_xo_3, qs_xo_4, qs_nl3],
        }
        return Response(data)

class IncidentesData1(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        qs_incidentes_reparado = Incidente.objects.filter(estado=True).count()
        qs_incidentes_pendiente = Incidente.objects.filter(estado=False).count()
#       qs_nl3 = Laptop.objects.filter(modelo=5).count()
#       qs_escuela_1 = Persona.objects.filter(escuela='1').count()
#       qs_escuela_2 = Persona.objects.filter(escuela='2').count()
#       qs_escuela_3 = Persona.objects.filter(escuela='3').count()
#       qs_count = User.objects.all().count()
        data_1 = {
            "labels": ["Reparados", "Pendientes"],
            "data": [qs_incidentes_reparado, qs_incidentes_pendiente],
        }
        return Response(data_1)

class IncidentesData2(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        qs_incidente_tipo_1 = Incidente.objects.filter(tipo_incidente=1).count()
        qs_incidente_tipo_2 = Incidente.objects.filter(tipo_incidente=2).count()
        qs_incidente_tipo_3 = Incidente.objects.filter(tipo_incidente=3).count()

        data_2 = {
            "labels": ["Revision", "Defecto", "Daño"],
            "data": [qs_incidente_tipo_1, qs_incidente_tipo_2, qs_incidente_tipo_3],
        }
        return Response(data_2)

class IncidentesData3(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        qs_incidente_componente_1 = Incidente.objects.filter(componente=1).count()
        qs_incidente_componente_2 = Incidente.objects.filter(componente=2).count()
        qs_incidente_componente_3 = Incidente.objects.filter(componente=3).count()
        qs_incidente_componente_4 = Incidente.objects.filter(componente=4).count()
        qs_incidente_componente_5 = Incidente.objects.filter(componente=5).count()
        qs_incidente_componente_6 = Incidente.objects.filter(componente=6).count()

        data_3 = {
            "labels": [
                "Pantalla", 
                "Teclado", 
                "Bateria",
                "Antena",
                "Touchpad",
                "Tarjeta madre"
                ],
            "data": [
                qs_incidente_componente_1, 
                qs_incidente_componente_2, 
                qs_incidente_componente_3,
                qs_incidente_componente_4,
                qs_incidente_componente_5,
                qs_incidente_componente_6
                ],
        }
        return Response(data_3)

templates/escuela/base_reporte.html
{% extends 'base/base2.html' %}

{% block content %}
<div class="starter-template">
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
        <canvas id="myChart" width="350" height="350">
            <script>
                $(document).ready(function(){
                {% block jquery %}{% endblock %}
                })
            </script>
        </canvas>
        </div>
        <div class="col-sm-3"></div>
    </div>
</div>

</main><!-- /.container -->
{% endblock content %}

templates/escuela/borrar_persona.html
{% extends 'base/base2.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}

	<h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'escuela:listar_persona' %}">Cancelar</a>
</form>
{% endblock %}

templates/escuela/crear_donante.html
{% extends 'base/base2.html' %}

{% block content %}

<form method="post">
	{% csrf_token %}
	{{form.as_p}}
	<button type="submit" class="btn btn-primary">Guardar</button>
	<a class= "btn btn-default" href="{% url 'escuela:listar_donante' %}">Cancelar</a>
</form>

{% endblock %}

templates/escuela/crear_escuela.html
{% extends 'base/base2.html' %}

{% block content %}

<form method="post">
	{% csrf_token %}
	{{form.as_p}}
	<button type="submit" class="btn btn-primary">Guardar</button>
	<a class= "btn btn-default" href="{% url 'escuela:listar_escuela' %}">Cancelar</a>
</form>

{% endblock %}

templates/escuela/crear_visita.html
{% extends 'base/base2.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="panel panel-warning">
	<div class="panel-heading">
		<h3 class="panel-title">Agregar visita al inventario</h3>
	</div>

	<div class="panel-body">
		<form method="post" novalidate autocomplete="off">
		{% csrf_token %}

		<form class="form-horizontal">
		<fieldset>
			<legend>Datos de la visita</legend>

			<div class="row">
				<div class="col-sm-2">
					{{ form.fecha|as_crispy_field }}
					<script>
						$(function () {
							$("#id_fecha").datepicker({
								format:'dd/mm/yyyy',
							});
						});
					</script>
				</div>				
				<div class="col-sm-5">
					{{ form.escuela|as_crispy_field }}
				</div>
				<div class="col-sm-5">
					{{ form.tipo_visita|as_crispy_field }}
				</div>
			</div>	

			<div class="row">
				<div class="col-sm-12">
					{{ form.titulo|as_crispy_field }}
				</div>
			</div>

			<div class="row">
				<div class="col-sm-12">
					{{ form.objetivo|as_crispy_field }}
				</div>
			</div>

			<div class="row">
				<div class="col-sm-12">
					{{ form.descripcion|as_crispy_field }}
				</div>
			</div>			

			<div class="row">
				<div class="col-sm-12">
					{{ form.avances|as_crispy_field }}
				</div>
			</div>			

			<div class="form-group">
				<!-- <button type="reset" class="btn btn-default">Limpiar</button> -->
				<a class= "btn btn-warning" href="{% url 'escuela:listar_visita' %}">Cancelar</a>
				<button type="submit" class="btn btn-primary">Guardar</button>
			</div>			

		</fieldset>
		</form>
		</form>
	</div>
</div>
{% endblock %}

templates/escuela/listar_donante.html
{% extends 'base/base2.html' %}

{% block content %}
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<form class="form-inline">
	<div class="form-group">
			<a href="{% url 'donante:crear_donante' %}" class="btn btn-primary btn-xs" role="button">Agregar</a>
			<a href="/admin/laptop/laptop/import/" class="btn btn-success btn-xs" role="button"> Importar masivamente</a>
			<input class="form-control input-sm" id="myInput" type="text" placeholder="Filtrar..">
	</div>
</form>

{% if object_list %}
<table class="table table-striped table-hover">
	<thead>
		<tr class="info">
		  <th style="text-align:center">#</th>
			<th style="text-align:center">Nombre</th>
			<th style="text-align:center">Direccion</th>
			<th style="text-align:center">Telefono</th>
			<th style="text-align:center">Email</th>
			<th style="text-align:center">Escuela</th>
			<th style="text-align:center">Donacion</th>
			<th style="text-align:center">Acciones</th>
		</tr>
	</thead>

	<tbody id="myTable">
		<ol>
		{% for donante in object_list %}
		<tr>
		  <td style="text-align:center">{{ forloop.counter }}</td>
			<td style="text-align:center">{{ donante.nombre }}</td>
			<td style="text-align:center">{{ donante.direccion }}</td>
			<td style="text-align:center">{{ donante.telefono }}</td>
			<td style="text-align:center">{{ donante.email }}</td>
			<td style="text-align:center">{{ donante.escuela }}</td>
			<td style="text-align:center">{{ donante.donacion }}</td>
			<td align="center">
				<a class="btn btn-primary btn-xs" href="{% url 'escuela:editar_donante' donante.id %}">Editar</a>
				<a class="btn btn-danger btn-xs" href="{% url 'escuela:borrar_donante' donante.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
	</ol>

		{% else %}
			<h1>No hay registros de donantes</h1>
		{% endif %}
	</tbody>
</table>

{% if is_paginated %}
  <ul class="pagination pagination-sm">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

templates/escuela/listar_persona.html
{% extends 'base/base2.html' %}

{% block content %}
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<form class="form-inline">
	<div class="form-group">
			<a href="{% url 'escuela:crear_persona' %}" class="btn btn-primary btn-xs" role="button">Agregar</a>
      <a href="/admin/escuela/persona/import" class="btn btn-success btn-xs" role="button"> Importar masivamente</a>
			<input class="form-control input-sm" id="myInput" type="text" placeholder="Filtrar..">
	</div>
</form>

{% if object_list %}
<table class="table table-bordered table-hover">
	<thead>
		<tr class="info">
			<th style="text-align:center">#</th>
			<th style="text-align:center">Nombre</th>
			<th style="text-align:center">Apellido</th>
			<th style="text-align:center">Telefono</th>
			<th style="text-align:center">XO Asignada</th>
			<th style="text-align:center">Escuela</th>
			<th style="text-align:center">Grado</th>
			<th style="text-align:center">Acciones</th>
		</tr>
	</thead>

  <tbody id="myTable">
    <ol>
		{% for persona in object_list %}
		<tr>
			<td style="text-align:center">{{ forloop.counter }}</td>
			<td style="text-align:center">{{ persona.nombre }}</td>
			<td style="text-align:center">{{ persona.apellido }}</td>
			<td style="text-align:center">{{ persona.telefono }}</td>
			<td style="text-align:center">{{ persona.laptop|default_if_none:'Ninguno' }}</td>
			<td style="text-align:center">{{ persona.escuela|default_if_none:'Ninguno' }}</td>
			<td style="text-align:center">{{ persona.grado|default_if_none:'Ninguno' }}</td>
		<td align="center">
				<a class="btn btn-primary btn-xs" href="{% url 'escuela:editar_persona' persona.id %}">Editar</a>
				<a class="btn btn-danger btn-xs" href="{% url 'escuela:borrar_persona' persona.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
    </ol>
		{% else %}
		<h1>No hay registros de personas</h1>
		{% endif %}
	</tbody>
</table>

{% if is_paginated %}
  <ul class="pagination pagination-sm">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

templates/escuela/listar_visitaa.html
{% extends 'base/base2.html' %}

<script>
  {% block jquery %}
  var endpoint = 'escuela/api/chart/data'

  $.ajax({
      method: "GET",
      url: endpoint,
      success: function(data){
          data: {
            labels: data.labels, #updated
            datasets: [{
                label: 'Votes per day',
                data: data.data, #updated
      },
      error: function(error_data){
        console.log(error_data)
      }
  })

  {% endblock %}
</script>