laptop/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from laptop.views import index, LaptopListar, LaptopCrear, LaptopEditar, LaptopBorrar, \
						 IncidenteListar, IncidenteCrear, IncidenteEditar, IncidenteBorrar

urlpatterns = [
#    url(r'^$', index, name='index'),
    url(r'^$', login_required(LaptopListar.as_view()), name='listar_laptop'),
    url(r'^listar/', login_required(LaptopListar.as_view()), name='listar_laptop'),
    url(r'^crear/', login_required(LaptopCrear.as_view()), name='crear_laptop'),
    
    url(r'^editar_laptop/(?P<pk>\d+)/$', login_required(LaptopEditar.as_view()), name='editar_laptop'),
    url(r'^borrar_laptop/(?P<pk>\d+)/$', login_required(LaptopBorrar.as_view()), name='borrar_laptop'),

    url(r'^listar_incidente/', login_required(IncidenteListar.as_view()), name='listar_incidente'),
    url(r'^crear_incidente/', login_required(IncidenteCrear.as_view()), name='crear_incidente'),

    url(r'^editar_incidente/(?P<pk>\d+)/$', login_required(IncidenteEditar.as_view()), name='editar_incidente'),
    url(r'^borrar_incidente/(?P<pk>\d+)/$', login_required(IncidenteBorrar.as_view()), name='borrar_incidente'),
]

racii/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

# password reset
from django.contrib.auth import views as auth_views

import django.views.defaults

def custom_page_not_found(request):
    return django.views.defaults.page_not_found(request, None)


urlpatterns = [
    url(r'^', include('laptop.urls', namespace='index')),
    url(r'^admin/', admin.site.urls),
    url(r'^laptop/', include('laptop.urls', namespace='laptop')),
    url(r'^escuela/', include('escuela.urls', namespace='escuela')),
    url(r'^donante/', include('donante.urls', namespace='donante')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    #url(r'^404/$', django.views.defaults.page_not_found, ),
    url(r'^404/', custom_page_not_found),
    # password_reset
    #url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    #url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.password_reset_confirm, name='password_reset_confirm'),
    #url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

laptop/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import datetime

# Create your models here.

class Laptop(models.Model):
	MODELOS_XO =(
		('1', 'XO1'),
		('2', 'XO1.5'),
		('3', 'XO1.75'),
		('4', 'XO4'),
		('5', 'NL3'),
	)
	serie = models.CharField(max_length=11)
	uuid = models.CharField(max_length=36)
	modelo = models.CharField(max_length=1, choices=MODELOS_XO)

	def __str__(self):
		return self.serie

	def modelo_detalle(self):
		return dict(Laptop.MODELOS_XO)[self.modelo]

	#def get_persona(self):
	#	Try:
	#		return Persona.objects.get(pk=self.forenea)
	#	except:
	#		return None

	class Meta:
		ordering = ('id',)

class Componente(models.Model):
	nombre = models.CharField(max_length=15)

	def __str__(self):
		return self.nombre

class Incidente(models.Model):
	TIPO_INCIDENTE_LAPTOP = (
		('1', 'Revision'),
		('2', 'Defecto'),
		('3', 'Daño'),
	)
	PRIORIDAD_INCIDENTE_LAPTOP = (
		('1', 'Urgente'),
		('2', 'Mayor'),
		('3', 'Menor'),
	)
	created_at = models.DateTimeField(auto_now_add=True)
	descripcion = models.CharField(max_length=50)
	detalle = models.TextField(blank=True)
	solucion = models.TextField(blank=True)
	laptop = models.ForeignKey(Laptop, blank=True)
	componente = models.ManyToManyField(Componente, blank=False)
	tipo_incidente = models.CharField(max_length=1, choices=TIPO_INCIDENTE_LAPTOP, default=1)
	prioridad_incidente = models.CharField(max_length=1, choices=PRIORIDAD_INCIDENTE_LAPTOP, default=3)
	# True - Reparado
	# False - Pendiente reparacion
	estado = models.BooleanField(default=False)

	def f_creacion(self):
		return self.created_at.strftime('%B %d %Y')

	def __str__(self):
		return '{} {} {} {}'.format(self.created_at, self.descripcion, self.detalle, self.laptop, self.componente)

	def tipo_incidente_detalle(self):
		return dict(Incidente.TIPO_INCIDENTE_LAPTOP)[self.tipo_incidente]

	def prioridad_incidente_detalle(self):
		return dict(Incidente.PRIORIDAD_INCIDENTE_LAPTOP)[self.prioridad_incidente]

	def estado_incidente_detalle(self):
		if self.estado == True:
			return 'Reparado'
		else:
			return 'Pendiente'

laptop/forms.py
from django import forms
from django.forms import ModelForm

from laptop.models import Laptop, Incidente

class LaptopForm(forms.ModelForm):
	class Meta:
		model = Laptop
		fields = [
			'serie',
			'uuid',
			'modelo',
		]
		labels = {
			'serie': 'Numero de serie XO',
			'uuid': 'UUID de la XO',
			'modelo': 'Modelo de la XO',
		}
		widgets = {
			'serie': forms.TextInput(attrs={'class':'form-control'}),
			'uuid': forms.TextInput(attrs={'class': 'form-control'}),
			'modelo': forms.Select(attrs={'class': 'form-control'}),
		}

class IncidenteForm(forms.ModelForm):
	class Meta:
		model = Incidente

		fields = [
			'descripcion',
			'laptop',
			'detalle',
			'componente',
			'tipo_incidente',
			'prioridad_incidente',
			'solucion',
			'estado',
		]
		labels = {
			'descripcion': 'Descripcion',
			'laptop': 'Laptop',
			'detalle': 'Detalle',
			'componente': 'Componentes',
			'tipo_incidente': 'Tipo incidente',
			'prioridad_incidente': 'Prioridad incidente',
			'solucion': 'Solucion',
			'estado': 'Raparada',
		}
		widgets = {
			'descripcion': forms.TextInput(attrs={
				'class':'form-control'
				}),
			'laptop': forms.Select(attrs={
				'class': 'selectpicker',
				'data-live-search':'true'
				}),
			'detalle': forms.Textarea(attrs={
				'rows': '4',
				'placeholder': 'Describa los detalles del problema en la laptop.'
				}),
			'solucion': forms.Textarea(attrs={
				'rows': '4',
				'placeholder': 'Describa los detalles de la repacion realizada a la laptop.'
				}),			
			'componente': forms.CheckboxSelectMultiple(attrs={
				'class': 'column-checkbox'
				}),
			'tipo_incidente': forms.Select(attrs={
				'class': 'form-control'
				}),
			'prioridad_incidente': forms.Select(attrs={
				'class': 'form-control'
				}),
			'estado': forms.CheckboxInput(),
		}

laptop/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect

from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy

from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from laptop.forms import LaptopForm, IncidenteForm
from laptop.models import Laptop, Incidente
from escuela.models import Persona

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def index(request):
	return render(request, 'base/base2.html')

class LaptopListar(ListView):
	model = Laptop
	template_name = 'laptop/listar_laptop.html'
	context_object_name = 'laptops'  # Default: object_list
	paginate_by = 10
	queryset = Laptop.objects.all()

#class LaptopListar(DetailView):

#	model = Laptop

#	template_name = 'laptop/listar_laptop.html'

#	def get_context_data(self, **kwargs):
#		context = super(LaptopListar, self).get_context_data(**kwargs)

#		return context

class LaptopCrear(CreateView):
	model = Laptop
	form_class = LaptopForm
	template_name = 'laptop/crear_laptop.html'
	success_url = reverse_lazy('laptop:listar_laptop')

class LaptopEditar(UpdateView):
	model = Laptop
	form_class = LaptopForm
	template_name = 'laptop/crear_laptop.html'
	success_url = reverse_lazy('laptop:listar_laptop')

class LaptopBorrar(DeleteView):
	model = Laptop
	template_name = 'laptop/borrar_laptop.html'
	success_url = reverse_lazy('laptop:listar_laptop')

class IncidenteListar(ListView):
	model = Incidente
	template_name = 'laptop/listar_incidente.html'
	context_object_name = 'incidentes'  # Default: object_list
	paginate_by = 10
	queryset = Incidente.objects.all()

class IncidenteCrear(CreateView):
	model = Incidente
	form_class = IncidenteForm
	template_name = 'laptop/crear_incidente.html'
	success_url = reverse_lazy('laptop:listar_incidente')

class IncidenteEditar(UpdateView):
	model = Incidente
	form_class = IncidenteForm
	template_name = 'laptop/crear_incidente.html'
	success_url = reverse_lazy('laptop:listar_incidente')

class IncidenteBorrar(DeleteView):
	model = Incidente
	template_name = 'laptop/borrar_incidente.html'
	success_url = reverse_lazy('laptop:listar_incidente')

templates/laptop/borrar_incidente.html
{% extends 'base/base2.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}

	<h3>¿Desea eliminar el registro de {{ object.laptop }}?</h3>
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'laptop:listar_incidente' %}">Cancelar</a>
</form>
{% endblock %}

templates/laptop/borrar_laptop.html
{% extends 'base/base2.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}

	<h3>¿Desea eliminar el registro de {{ object.serie }}?</h3>
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'laptop:listar_laptop' %}">Cancelar</a>
</form>
{% endblock %}

templates/laptop/crear_incidente.html
{% extends 'base/base2.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="panel panel-danger">
	<div class="panel-heading">
		<h3 class="panel-title">Crear incidente de la XO - </h3>
	</div>

	<div class="panel-body">
		<form method="post" novalidate>
		{% csrf_token %}

		<form class="form-horizontal">
		<fieldset>
			<legend>Descripcion del incidente</legend>

			<div class="row">
				<div class="col-sm-12">
					{{ form.descripcion|as_crispy_field }}
				</div>
			</div>

			<div class="row">
				<div class="col-sm-3">
					{{ form.laptop|as_crispy_field }}
				</div>
				<div class="col-sm-3">
					{{ form.tipo_incidente|as_crispy_field }}
				</div>
				<div class="col-sm-3">
					{{ form.prioridad_incidente|as_crispy_field }}
				</div>
				<div class="col-sm-3">
					{{ form.componente|as_crispy_field }}
				</div>
			</div>
			
			<div class="row">
				<div class="col-xs-12">
					{{ form.detalle|as_crispy_field }}
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12">
					{{ form.solucion|as_crispy_field }}
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12">
					{{ form.estado|as_crispy_field }}
				</div>
			</div>

			<div class="form-group">
				<div>
					<button type="reset" class="btn btn-default">Limpiar</button>
					<a class= "btn btn-warning" href="{% url 'laptop:listar_incidente' %}">Cancelar</a>
					<button type="submit" class="btn btn-primary">Guardar</button>
				</div>
			</div>

		</fieldset>
		</form>
	</div>
</div>

{% endblock %}

templates/laptop/crear_laptop.html
{% extends 'base/base2.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">Agregar laptop al inventario</h3>
	</div>

	<div class="panel-body">
		<form method="post" novalidate>
		{% csrf_token %}

		<form class="form-horizontal">
		<fieldset>
			<legend>Datos de la laptop</legend>

			<div class="row">
				<div class="col-sm-4">
					{{ form.serie|as_crispy_field }}
				</div>
				<div class="col-sm-4">
					{{ form.uuid|as_crispy_field }}
				</div>
				<div class="col-sm-4">
					{{ form.modelo|as_crispy_field }}
				</div>
			</div>
		
			<div class="form-group">
				<div>
					<button type="reset" class="btn btn-default">Limpiar</button>
					<a class= "btn btn-warning" href="{% url 'laptop:listar_laptop' %}">Cancelar</a>
					<button type="submit" class="btn btn-primary">Guardar</button>
				</div>
			</div>

		</fieldset>
		</form>

	</div>

</div>

{% endblock %}

templates/laptop/listar_incidente.html
{% extends 'base/base2.html' %}

{% block content %}

<form class="form-inline">
	<div class="form-group">
		<a class="btn btn-success btn-xs" href="{% url 'laptop:crear_incidente' %}">Agregar</a>
	</div>
</form>

{% if object_list %}
<div class="table-responsive">
<table class="table table-bordered table-hover">
	<thead>
		<tr class="active">
			<th style="text-align:center; vertical-align:middle">#</th>
			<th style="text-align:center; vertical-align:middle">ID</th>
			<th style="text-align:center; vertical-align:middle">Estado</th>
			<th style="text-align:center; vertical-align:middle">Descripcion</th>			
			<th style="text-align:center; vertical-align:middle">Fecha reporte</th>
			<th style="text-align:center; vertical-align:middle">Laptop</th>
			<th style="text-align:center; vertical-align:middle">Estudiante</th>
			<th style="text-align:center; vertical-align:middle">Escuela</th>
			<th style="text-align:center; vertical-align:middle">Grado</th>
			<th style="text-align:center; vertical-align:middle">Detalle</th>
			<th style="text-align:center; vertical-align:middle">Tipo</th>
			<th style="text-align:center; vertical-align:middle">Prioridad</th>
			<th style="text-align:center; vertical-align:middle">Componentes</th>
			<th style="text-align:center; vertical-align:middle">Acciones</th>
		</tr>
	</thead>
	<ol>
		{% for incidente in object_list %}
		{% if incidente.estado is True %}
			<tr class="success">
				<td style="text-align:center">{{ forloop.counter }}</td>
				<td style="text-align:center">{{ incidente.id }}</td>
				<td style="text-align:center">{{ incidente.estado_incidente_detalle }}</td>
				<td style="text-align:center">{{ incidente.descripcion}}</td>
				<td style="text-align:center">{{ incidente.created_at|date:"d M Y" }}</td>
				<td style="text-align:center">{{ incidente.laptop }}</td>
				<td style="text-align:center">{{ incidente.laptop.persona.nombre }}</td>
				<td style="text-align:center">{{ incidente.laptop.persona.escuela }}</td>
				<td style="text-align:center">{{ incidente.laptop.persona.grado }}</td>
				<td style="text-align:center">{{ incidente.detalle }}</td>
				<td style="text-align:center">{{ incidente.tipo_incidente_detalle }}</td>
				<td style="text-align:center">{{ incidente.prioridad_incidente_detalle }}</td>
				<td style="text-align:center">
					{% for componente in incidente.componente.all %}
					<span class="label label-primary">
						{{componente.nombre}}
					</span>
					{% endfor %}
				</td>
				<td align="center">
					<a class="far fa-edit" data-toggle="tooltip" title="Editar" href="{% url 'laptop:editar_incidente' incidente.id %}"></a>
					<a class="far fa-trash-alt" data-toggle="tooltip" title="Eliminar" href="{% url 'laptop:borrar_incidente' incidente.id %}"}></i>
				</td>
			</tr>
		{% else %}
			<tr class="warning">
				<td style="text-align:center">{{ forloop.counter }}</td>
				<td style="text-align:center">{{ incidente.id }}</td>
				<td style="text-align:center">{{ incidente.estado_incidente_detalle }}</td>
				<td style="text-align:center">{{ incidente.descripcion}}</td>
				<td style="text-align:center">{{ incidente.created_at|date:"d M Y" }}</td>
				<td style="text-align:center">{{ incidente.laptop }}</td>
				<td style="text-align:center">{{ incidente.laptop.persona.nombre }}</td>
				<td style="text-align:center">{{ incidente.laptop.persona.escuela }}</td>
				<td style="text-align:center">{{ incidente.laptop.persona.grado }}</td>
				<td style="text-align:center">{{ incidente.detalle }}</td>
				<td style="text-align:center">{{ incidente.tipo_incidente_detalle }}</td>
				<td style="text-align:center">{{ incidente.prioridad_incidente_detalle }}</td>
				<td style="text-align:center">
					{% for componente in incidente.componente.all %}
					<span class="label label-primary">
						{{componente.nombre}}
					</span>
					{% endfor %}
				</td>
				<td align="center">
					<a class="far fa-edit" data-toggle="tooltip" title="Editar" href="{% url 'laptop:editar_incidente' incidente.id %}"></a>
					<a class="far fa-trash-alt" data-toggle="tooltip" title="Eliminar" href="{% url 'laptop:borrar_incidente' incidente.id %}"}></i>
				</td>
			</tr>
		{% endif %}		
		{% endfor %}
	</ol>
	{% else %}
		<h1>No hay registros de incidentes</h1>
	{% endif %}
</table>
</div>

{% if is_paginated %}
  <ul class="pagination pagination-sm">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

templates/laptop/listar_laptop.html
{% extends 'base/base2.html' %}

{% block content %}
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<form class="form-inline">
	<div class="form-group">
			<a href="{% url 'laptop:crear_laptop' %}" class="btn btn-primary btn-xs" role="button">Agregar</a>
			<a href="/admin/laptop/laptop/import/" class="btn btn-success btn-xs" role="button"> Importar masivamente</a>
			<input class="form-control input-sm" id="myInput" type="text" placeholder="Filtrar..">
	</div>
</form>

{% if object_list %}
<table class="table table-bordered table-hover">
	<thead>
		<tr class="info">
		  <th style="text-align:center">#</th>
			<th style="text-align:center">Serie</th>
			<th style="text-align:center">Persona</th>
			<th style="text-align:center">Escuela</th>
			<th style="text-align:center">Grado</th>
			<th style="text-align:center">Modelo</th>
			<th style="text-align:center">UUID</th>
			<th style="text-align:center">Acciones</th>
		</tr>
	</thead>

    <tbody id="myTable">
      <ol>
		{% for laptop in object_list %}
    <tr>
		  <td style="text-align:center">{{ forloop.counter }}</td>
			<td style="text-align:center">{{ laptop.serie|upper}}</td>
			<td style="text-align:center">{{ laptop.persona.nombre}} {{ laptop.persona.apellido}}</td>
			<td style="text-align:center">{{ laptop.persona.escuela|default_if_none:'Ninguno'}}</td>
			<td style="text-align:center">{{ laptop.persona.grado|default_if_none:'Ninguno'}}</td>
			<td style="text-align:center">{{ laptop.modelo_detalle }}</td>
			<td style="text-align:center">{{ laptop.uuid|upper}}</td>
			<td align="center">
				<a class="btn btn-primary btn-xs" href="{% url 'laptop:editar_laptop' laptop.id %}"> Editar</a>
            	<a class="btn btn-danger btn-xs" href="{% url 'laptop:borrar_laptop' laptop.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
    </ol>

		{% else %}
			<h1>No hay registros de laptops</h1>
		{% endif %}
	</tbody>
</table>

{% if is_paginated %}
  <ul class="pagination pagination-sm">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}